/*
 * SPDX-FileCopyrightText: 2020 Stalwart Labs LLC <hello@stalw.art>
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-SEL
 */

use crate::{
    inbound::dkim::DkimSign,
    queue::{
        MessageSource,
        spool::{QueueParams, SmtpSpool},
    },
};
use common::{Server, expr::if_block::IfBlock, ipc::ReportingEvent};

pub trait MtaReportSend: Sync + Send {
    fn send_report(
        &self,
        from_addr: &str,
        rcpts: impl Iterator<Item = impl AsRef<str> + Sync + Send> + Sync + Send,
        report: Vec<u8>,
        sign_config: &IfBlock,
        send_spread_secs: u64,
        parent_session_id: u64,
    ) -> impl Future<Output = ()> + Send;

    fn send_autogenerated(
        &self,
        from_addr: impl AsRef<str> + Sync + Send,
        rcpts: impl Iterator<Item = impl AsRef<str> + Sync + Send> + Sync + Send,
        raw_message: Vec<u8>,
        sign_config: Option<&IfBlock>,
        parent_session_id: u64,
    ) -> impl Future<Output = ()> + Send;

    fn schedule_report(
        &self,
        report: impl Into<ReportingEvent> + Sync + Send,
    ) -> impl Future<Output = ()> + Send;
}

impl MtaReportSend for Server {
    async fn send_report(
        &self,
        from_addr: &str,
        rcpts: impl Iterator<Item = impl AsRef<str> + Sync + Send> + Sync + Send,
        report: Vec<u8>,
        sign_config: &IfBlock,
        send_spread_secs: u64,
        parent_session_id: u64,
    ) {
        // Build message
        let mut message = self.new_message(from_addr, parent_session_id);
        for rcpt_ in rcpts {
            message.add_expanded_recipient(rcpt_.as_ref(), self).await;
        }

        // Spread delivery over a random point in the caller's window, so that
        // reports for many domains are not all sent at the same instant.
        if send_spread_secs > 0 {
            #[cfg(not(feature = "test_mode"))]
            {
                use common::config::smtp::queue::QueueExpiry;
                use rand::Rng;

                let delivery_time = rand::rng().random_range(0u64..send_spread_secs);
                for rcpt in &mut message.message.recipients {
                    rcpt.retry.due += delivery_time;
                    rcpt.notify.due += delivery_time;
                    if let QueueExpiry::Ttl(expires) = &mut rcpt.expires {
                        *expires += delivery_time;
                    }
                }
            }
        }

        // Queue message
        let dkim_signers = self
            .eval_signers(sign_config, &message.message, parent_session_id)
            .await;
        message
            .queue(
                QueueParams::new(&report, parent_session_id, self, MessageSource::Report)
                    .with_dkim_signers(dkim_signers),
            )
            .await;
    }

    async fn send_autogenerated(
        &self,
        from_addr: impl AsRef<str> + Sync + Send,
        rcpts: impl Iterator<Item = impl AsRef<str> + Sync + Send> + Sync + Send,
        raw_message: Vec<u8>,
        sign_config: Option<&IfBlock>,
        parent_session_id: u64,
    ) {
        // Build message
        let mut message = self.new_message(from_addr.as_ref(), parent_session_id);
        for rcpt in rcpts {
            message.add_expanded_recipient(rcpt, self).await;
        }

        // Queue message
        let dkim_signers = if let Some(sign_config) = sign_config {
            self.eval_signers(sign_config, &message.message, parent_session_id)
                .await
        } else {
            None
        };
        message
            .queue(
                QueueParams::new(
                    &raw_message,
                    parent_session_id,
                    self,
                    MessageSource::Autogenerated,
                )
                .with_dkim_signers(dkim_signers),
            )
            .await;
    }

    async fn schedule_report(&self, report: impl Into<ReportingEvent> + Sync + Send) {
        if self.inner.ipc.report_tx.send(report.into()).await.is_err() {
            trc::event!(
                Server(trc::ServerEvent::ThreadError),
                CausedBy = trc::location!(),
                Details = "Failed to send event to ReportScheduler"
            );
        }
    }
}
